### ISSUE TITLE
Is bit-shuffle supposed to work with hdf5?

### ISSUE THREAD

**Issue by aldanor** [Blosc/hdf5-blosc#6] opened 2015-08-27 10:58 UTC
I've built a thin Cython wrapper around blosc_filter to see if it plays well with h5py and indeed it does, except for the bit-shuffle which often causes segfaults. Here's a reproducible one:

``` python
import h5py
import numpy as np

import h5blosc
h5blosc.register_blosc()

np.random.seed(42)
shape = (100, 2)
data = np.random.random_integers(-32768, 32767, shape).astype(np.int16)

f = h5py.File('test', driver='core', backing_store=False)
f.create_dataset('data', data=data, compression=32001,
                 compression_opts=(0, 0, 0, 0, 3, 2, 0))  # blosc:blosclz, level=3, bit-shuffle
f.close()
```

results in

``` console
*** Error in `python': free(): invalid next size (normal): 0x000000000203a2e0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7d1fd)[0x7f239d97a1fd]
/home/smirnov/dev/h5blosc/env/lib/libblosc_filter.so(blosc_filter+0xf6)[0x7f238ec7e366]
/home/smirnov/dev/h5blosc/env/lib/python3.4/site-packages/h5py/../../../libhdf5.so.10(H5Z_pipeline+0x354)[0x7f2396f4a544]
```

or

``` console
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6cc656b in malloc_consolidate (av=av@entry=0x7ffff7004760 <main_arena>) at malloc.c:4121
4121                unlink(av, p, bck, fwd);
```

I then try to use pytables to register the blosc filter and it seems like it doesn't allow `BLOSC_BITSHUFFLE`:

``` console
`shuffle` parameter must be either 0 or 1!
```

If it's not supposed to work, should it be validated the same in `blosc_filter.c` as well?

**Comment by FrancescAlted** [comment] 2015-08-27 11:27
Well, the bitshuffle filter backport is still pretty new (it appeared for first time in C-Blosc 1.7.0), and although all the tests in c-blosc itself pass, I have never tried it in PyTables yet (which might also reproduce the issue that you are having).  I think we should try to figure out what the problem is and fix it.  Meanwhile, its use should be discouraged for production purposes I guess.

**Comment by aldanor** [comment] 2015-08-27 12:48
I see, thanks. After digging a bit more, here's the smallest example I could find.

This works:

``` python
f.create_dataset('data', data=np.zeros(63, np.int16), compression=32001,
                 compression_opts=(0, 0, 0, 0, 3, 2, 0))  # blosc:blosclz, level=3, bit-shuffle
```

This segfaults:

``` python
f.create_dataset('data', data=np.zeros(64, np.int16), compression=32001,
                 compression_opts=(0, 0, 0, 0, 3, 2, 0))  # blosc:blosclz, level=3, bit-shuffle
```

**Comment by hyoklee** [comment] 2015-11-09 22:22
@aldanor, how did you make h5py work with blosc? Do you have any documentation for the steps involved?

**Comment by aldanor** [comment] 2015-11-10 00:28
@hyoklee Basically wrote a little cython wrapper around the blosc-hdf5 plug-in that (a) lets you call the register function from within Python and (b) converts parameter tuples from humanized format to the one blosc-hdf5 understands. Idk, I could probably publish that but it's quite trivial really.

**Comment by FrancescAlted** [comment] 2016-04-15 09:42
@aldanor , latest C-Blosc (currently 1.8.1) should have fixed any pending issues with BITSHUFFLE (at least, I was able to successfully roundtrip several thousands of TB with it activated).  I am going to close this, but feel free to reopen this in case you still get problems.

**Closed as completed by FrancescAlted** 2016-04-15 09:42 UTC
